version: 2
seeds:
  - name: customers
    description: One record per customer # add a description to the table
    columns:
      - name: customer_id
        description: Primary key # add a description to column customer_id
        tests:
          - unique
          - not_null
      - name: first_order_date
        description: NULL when a customer has not yet placed an order. # add a description to column first_order_date

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
  - name: customer_order_history
    description: >
      In this table, we describe the purchase history of all customers. We 

    columns:
      - name: customer_id
        description: the id of the customer
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: first_order_date
        description: The date of the first purcharse
      - name: most_recent_order_date
        description: The date of the last purcharse